var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{attrs:{"id":"app"}},[_c('background-component'),_vm._v(" "),_c('home-component'),_vm._v(" "),_c('intro-component'),_vm._v(" "),_vm._m(0),_vm._v(" "),_c('div',{staticClass:"feature-fix-container"},_vm._l((_vm.features),function(feature,key){return _c('feature-component',{key:key,class:( _obj = { active:feature.active}, _obj['feat' + (key + 1) ] = true, _obj ),attrs:{"feature":feature},on:{"changeActive":function($event){_vm.changeActive($event)}}})
var _obj;})),_vm._v(" "),_vm._m(1),_vm._v(" "),_c('div',{staticClass:"footer-fixed-stuff"},[_vm._m(2),_vm._v(" "),_vm._m(3),_vm._v(" "),_c('div',{staticClass:"footer-buyWatch-btn-outer"},[_c('a',{staticClass:"footer-buyWatch-btn bigItUp",attrs:{"href":"https://www.viita-watches.com/product/viita-titan-hrv/","target":"_blank","rel":"noopener"},on:{"mouseenter":_vm.funcFooterBtn,"mouseleave":_vm.funcFooterBtnOut}},[_c('div',{staticClass:"footer-btn-hover-bg"}),_vm._v(" "),_c('div',{staticClass:"footer-buyWatch-txt"},[_vm._v("\n          SHOP NOW\n        ")])]),_vm._v(" "),_c('a',{staticClass:"imprint",attrs:{"href":"https://www.viita-watches.com/imprint/?noredirect=en_US","target":"_blank","rel":"noopener"}},[_vm._v("IMPRINT")])])]),_vm._v(" "),_c('footer-component'),_vm._v(" "),_c('interface-component'),_vm._v(" "),_vm._m(4),_vm._v(" "),_c('div',{staticClass:"navigation"},_vm._l((_vm.bullets),function(bullet,key){return _c('bullet-component',{key:key,class:( _obj = { active:bullet.active}, _obj['bullet' + (key + 1) ] = true, _obj ),attrs:{"bullet":bullet},on:{"getBulletNumber":function($event){_vm.getBulletNumber($event)}}})
var _obj;}))],1)}
var staticRenderFns = [function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"feature-scrolltrigger"},[_c('div',{staticClass:"fake-feature fake1"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake2"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake3"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake4"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake5"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake6"}),_vm._v(" "),_c('div',{staticClass:"fake-feature fake7"})])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"intro-fixed-watch-container"},[_c('div',{staticClass:"intro-watch-outer"},[_c('div',{staticClass:"intro-twister"},[_c('img',{staticClass:"intro-watch",attrs:{"src":"/src/assets/viita_titan_main.png","alt":"VIITA Titan"}})])]),_vm._v(" "),_c('div',{staticClass:"intro-watch-outer"},[_c('div',{staticClass:"intro-twister"},[_c('img',{staticClass:"intro-watch2",attrs:{"src":"/src/assets/viita_titan_housing2.png","alt":"VIITA Titan Housing"}})])]),_vm._v(" "),_c('div',{staticClass:"intro-watch-outer"},[_c('div',{staticClass:"intro-twister"},[_c('img',{staticClass:"intro-watch3",attrs:{"src":"/src/assets/viita_titan_ceramicbezel.png","alt":"VIITA CERAMIC BEZEL"}})])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"footer-megaText-container"},[_c('div',{staticClass:"footer-megaText-box"},[_c('div',{staticClass:"footer-megaText-scaler"},[_c('div',{staticClass:"footer-megaText"},[_vm._v(" BUY ")])])])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"footer-watch-outer"},[_c('div',{staticClass:"footer-twister"},[_c('img',{staticClass:"footer-watch",attrs:{"src":"/src/assets/viita_titan_housing2.png","alt":"VIITA Titan Housing"}})])])},function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"theBall-outer"},[_c('div',{staticClass:"theBall"})])}]
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-192581aa","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue
// module id = 49
// module chunks = 0