pool.descriptions = {
    domains: "The Ross Spiral Curriculum is a literary narrative of the evolution of human consciousness. It is taught chronologically through the grades as a dynamic system expanding in complexity. Cultural History is at the core of the Ross Curriculum, interwoven with all of the other domains. While each discipline offers its own rigorous curriculum, integration between domains creates a dynamic choreography of learning. Using this interdisciplinary approach, each grade focuses on a particular historical period and theme. The Spiral provides a cohesive architecture for analysis of the past as a dynamical system and enables students to more fully understand the present while envisioning the future.",

    grades: "In each grade, students examine the thematic development of a particular historical period and study this theme across global cultures. Students explore the cultural ecology and mathematical mentality of the period, to understand how the particular attributes of a society developed or changed over time. \nGrades are composed of a series of integrated units—a theme of study within a course whose duration varies from several weeks to a trimester. Units are comprised of Learning Experiences and Integrated Projects, equivalent to one or more lessons on a specific topic.",

    ecologies: "One of two integrated narratives foundational to the Ross Spiral Curriculum, the Cultural Ecologies consider culture as an ecosystem. Its parts—such as literature, visual arts, musical creations and performance, mathematical developments and applications, scientific discoveries, economics—are interconnected like the flora, fauna, and environment in a biospheric ecosystem. Local cultural microsystems are interconnected in a global cultural macrosystem, linked by trade and cultural diffusion. Each cultural ecology is characterized by attributes, including a dominant mathematical mentality. Cultural ecologies are introduced at different grade levels, from Sylvan / Savannahan/Lacustrian / Glacial (grade 3), to Post-Glacial (grade 4), to Riverine (grade 5), to Transcontinental (grades 6–8), to Oceanic (grades 9–11), to Biospheric (grade 11).",

    mentalities: "Mathematical mentalities, one of two integrated narratives comprising the Ross Spiral Curriculum, represent the dominant style of mathematical cognition exhibited by individuals in a cultural ecology, characterizing an entire cultural ecology by its mathematical style. Mathematical mentalities appear chronologically along the Spiral of Cultural History and are introduced in different grade levels, from Arithmetic (grades 3–5), to Geometric (grades 5–7), to Algebraic (grade 8), to Dynamical (grades 9–11), to Complex Dynamical (grade 11). Mathematical mentalities coevolve with cultural ecologies and, once emergent, remain but are no longer the dominant style of mathematical cognition, instead giving way to the next mentality that emerges. ",

    threads: "Threads are important ideas or a cultural phenomena that recur throughout the Spiral Curriculum. If you trace a vertical conceptual path through time in the spiral curriculum, what emerges is a thread. These threaded concepts might be narrow or broad, disciplinary or interdisciplinary. Examples include art and architecture; communication and media; cosmology; migration; spirituality and sacred beliefs; sustainability; and trade and commerce."


};